name: Go Services CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  go-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ services/auth-service, services/venue-service, services/parking-service, services/valet-service ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Vet & Test
        working-directory: ${{ matrix.service }}
        run: |
          go version
          go vet ./...
          go test ./...

