openapi: 3.0.3
info:
  title: Bytspot Admin API
  version: 0.1.0
servers:
  - url: http://localhost:8093
paths:
  /admin/venues:
    get:
      summary: List venues
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Venue'
    post:
      summary: Create a venue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VenueCreate'
      responses:
        '201': { description: Created }
        '400': { description: Bad Request }
  /admin/analytics/summary:
    get:
      summary: Basic analytics summary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  users: { type: integer }
                  venues: { type: integer }
                  likes: { type: integer }
  /admin/users:
    get:
      summary: List users (paged)
      parameters:
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 20 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
components:
  schemas:
    Venue:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        subtitle: { type: string }
        rating: { type: number }
        distance: { type: string }
        price: { type: string }
    VenueCreate:
      type: object
      required: [title]
      properties:
        title: { type: string }
        subtitle: { type: string }
        price: { type: string }
    User:
      type: object
      properties:
        id: { type: string }
        email: { type: string }
        name: { type: string }

